# Check out https://docs.codemagic.io/yaml/yaml/ for more information

workflows:
    flutter-widget:
        name: Flutter Widget
        environment:
            flutter: dev
        scripts:
            - echo 'previous step'
            - name: 'Flutter drive web test'
        script: |
            chromedriver --port=4444 &
            flutter config --enable-web
            flutter drive --target=test_driver/button_pressing.dart -d chrome --browser-name chrome --release
              
