name: Dart CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'stable' or 'dev' or 'beta'
    - name: Configure Flutter
      run: |
        flutter config --enable-web
        flutter pub get
    - name: Run tests
      run: pub run test
    - name: build web
      run: flutter build web


