# This is a basic workflow to help you get started with Actions

name: prod CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release/prod-* ]
  pull_request:
    branches: [ release/prod-* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Flutter github actions
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # or: 'stable' or 'dev' or 'beta'

      - name: Configure Flutter and build codes
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web
